version: "3"

services:
  tensurf-ui:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
networks:
  default:
    external: true
    name: tensurf-network
